# The Okta software accompanied by this notice is provided pursuant to the following terms:
# Copyright © 2025-Present, Okta, Inc.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

"""
Orchestrator MCP Tools — CSP Constraint-Solver Orchestrator.

Three tools let the LLM delegate multi-step Okta workflows to a
server-side constraint solver instead of reasoning about the correct
API sequence itself.

Workflow for the LLM:
    1. Call orchestrator_plan_for_goal  — describe WHAT you want (goal),
       the solver figures out HOW (action sequence) and builds an
       executable plan.  Always returns a plan_id.
    2. Call orchestrator_execute        — run the plan the solver built.
    3. Call orchestrator_context        — inspect session state or results.

There are NO predefined workflows.  Every workflow is dynamically
generated by the CSP constraint solver from the knowledge graph.
The LLM only needs to express the desired end-state (goal predicates)
and the solver automatically discovers the minimal action sequence.
"""

from typing import Optional

from loguru import logger
from mcp.server.fastmcp import Context

from okta_mcp_server.server import mcp
from okta_mcp_server.tools.orchestrator.engine import (
    Plan,
    PlanStatus,
    Step,
    create_plan,
    execute_plan,
    get_session,
    _serialise,
)
from okta_mcp_server.tools.orchestrator.knowledge_graph import get_knowledge_graph
from okta_mcp_server.tools.orchestrator.planner import (
    plan_for_state,
)


# @mcp.tool()  # Temporarily disabled — CSP planner replaces manual KG queries
async def orchestrator_query_graph(
    ctx: Context,
    query_type: str,
    entity_type: Optional[str] = None,
    operation: Optional[str] = None,
    tag: Optional[str] = None,
    action: Optional[str] = None,
    available_params: Optional[str] = None,
    max_depth: Optional[int] = None,
    start_action: Optional[str] = None,
    end_action: Optional[str] = None,
) -> dict:
    """Query the knowledge graph dynamically to discover tools and connections.

    The graph contains all Okta SDK actions as nodes and data-flow dependencies
    as edges.  Use different query_type values to explore the graph:

    Parameters:
        query_type (str, required): The type of query. One of:
            - "tools"         — filter tools by entity_type, operation, and/or tag
            - "callable"      — given params you have, which tools can you call?
            - "reachable"     — BFS from start_action: what tools can be reached?
            - "dependencies"  — reverse BFS: what must run before this action?
            - "path"          — shortest data-flow path between two actions
            - "node"          — get full details of a single tool node
            - "stats"         — graph statistics
            - "full"          — dump entire graph (nodes + edges)

        entity_type (str, optional): Filter by entity: "user", "group", "application"
        operation (str, optional): Filter by operation: "read", "write", "delete"
        tag (str, optional): Filter by tag: "lookup", "lifecycle", "membership", etc.
        action (str, optional): Tool action name for "node" or "dependencies" queries
        available_params (str, optional): Comma-separated param names for "callable"
        max_depth (int, optional): Max traversal depth for "reachable" (default 10)
        start_action (str, optional): Start node for "reachable" or "path"
        end_action (str, optional): End node for "path"

    Returns:
        Dict with query results — tools, edges, paths, or stats depending on query_type.

    Examples:
        # What user tools exist?
        orchestrator_query_graph(query_type="tools", entity_type="user")

        # I have a user_id — what can I call?
        orchestrator_query_graph(query_type="callable", available_params="user_id")

        # What can I reach from get_user?
        orchestrator_query_graph(query_type="reachable", start_action="get_user")

        # What needs to run before I can call deactivate_user?
        orchestrator_query_graph(query_type="dependencies", action="deactivate_user")

        # Path from get_user to remove_user_from_group?
        orchestrator_query_graph(query_type="path", start_action="get_user", end_action="remove_user_from_group")
    """
    kg = get_knowledge_graph()
    qt = query_type.lower()

    logger.info(f"orchestrator_query_graph: type='{qt}'")

    if qt == "tools":
        tools = kg.query_tools(entity_type=entity_type, operation=operation, tag=tag)
        return {"tools": tools, "count": len(tools)}

    if qt == "callable":
        params = [p.strip() for p in (available_params or "").split(",") if p.strip()]
        tools = kg.query_callable_tools(params)
        return {"callable_tools": tools, "count": len(tools), "given_params": params}

    if qt == "reachable":
        if not start_action:
            return {"error": "reachable query requires start_action"}
        return kg.query_reachable(start_action, max_depth=max_depth or 10)

    if qt == "dependencies":
        target = action or end_action
        if not target:
            return {"error": "dependencies query requires action or end_action"}
        return kg.query_dependencies(target)

    if qt == "path":
        if not start_action or not end_action:
            return {"error": "path query requires start_action and end_action"}
        path = kg.query_path(start_action, end_action)
        if path is None:
            return {"path": None, "message": f"No path from '{start_action}' to '{end_action}'"}
        return {"path": path, "length": len(path)}

    if qt == "node":
        if not action:
            return {"error": "node query requires action"}
        node = kg.get_node(action)
        if not node:
            return {"error": f"Unknown action '{action}'"}
        upstream = kg.get_upstream(action)
        downstream = kg.get_downstream(action)
        return {
            "node": kg._serialise_node(node),
            "upstream": upstream,
            "downstream": downstream,
        }

    if qt == "stats":
        return kg.get_stats()

    if qt == "full":
        return kg.to_dict()

    return {"error": f"Unknown query_type '{query_type}'. Use: tools, callable, reachable, dependencies, path, node, stats, full"}


# @mcp.tool()  # Temporarily disabled — CSP planner replaces manual plan building
async def orchestrator_build_plan(
    ctx: Context,
    actions: str,
    target_identifier: str,
    workflow_name: Optional[str] = None,
    description: Optional[str] = None,
    extra_params: Optional[str] = None,
) -> dict:
    """Build an execution plan from an ordered list of actions you chose.

    YOU decide the sequence of tools after querying the graph.  The KG
    automatically resolves parameter bindings (e.g. step 1's user ID feeds
    into step 2) based on its edge metadata.  You just provide the ordered
    action names.

    Parameters:
        actions (str, required): Comma-separated ordered action names.
            Example: "get_user,list_user_groups,remove_user_from_group,deactivate_user"
        target_identifier (str, required): The primary identifier (e.g. user email/ID).
        workflow_name (str, optional): A name for this workflow (default: "dynamic_workflow").
        description (str, optional): Human-readable description of what this does.
        extra_params (str, optional): Additional static params as "key=value,key=value".
            These override auto-resolved bindings on the first step.

    Returns:
        Dict with plan preview ready for orchestrator_execute.

    Example:
        orchestrator_build_plan(
            actions="get_user,list_user_groups,remove_user_from_group,deactivate_user",
            target_identifier="john@acme.com",
            workflow_name="offboard",
            description="Offboard john: remove from groups and deactivate"
        )
    """
    kg = get_knowledge_graph()

    action_list = [a.strip() for a in actions.split(",") if a.strip()]
    if not action_list:
        return {"error": "No actions provided. Pass comma-separated action names."}

    logger.info(f"orchestrator_build_plan: actions={action_list}, target='{target_identifier}'")

    # Let the KG resolve wiring (param bindings + for_each) from edges
    try:
        step_dicts = kg.build_execution_chain(action_list)
    except ValueError as exc:
        return {"error": str(exc)}

    # Parse extra_params with optional action-targeting.
    extra: dict = {}
    targeted_params: dict[str, dict[str, str]] = {}
    if extra_params:
        for pair in extra_params.split(","):
            if "=" in pair:
                k, v = pair.split("=", 1)
                k = k.strip()
                v = v.strip()
                if k.startswith("@") and ":" in k:
                    action_target, real_key = k[1:].split(":", 1)
                    targeted_params.setdefault(
                        action_target.strip(), {}
                    )[real_key.strip()] = v
                else:
                    extra[k] = v

    # Inject the target identifier into the first step's required params
    first_node = kg.get_node(action_list[0])
    if first_node:
        _PROFILE_FIELDS = {
            "firstName", "lastName", "email", "login", "mobilePhone",
            "secondEmail", "displayName", "nickName", "title",
            "department", "organization", "userType",
            "name", "description",
        }
        if first_node.required_params:
            for param in first_node.required_params:
                if param == "profile" and extra.keys() & _PROFILE_FIELDS:
                    profile_dict = {k: extra.pop(k) for k in list(extra) if k in _PROFILE_FIELDS}
                    step_dicts[0]["params"]["profile"] = profile_dict
                else:
                    step_dicts[0]["params"][param] = target_identifier
        elif target_identifier:
            for param in (first_node.optional_params or []):
                if param.endswith("_id") or param == "name":
                    step_dicts[0]["params"][param] = target_identifier
                    break

    # Apply action-targeted params to their specific steps.
    if targeted_params:
        for step_dict in step_dicts:
            action_name = step_dict["action"]
            if action_name in targeted_params:
                for k, v in targeted_params[action_name].items():
                    step_dict["params"][k] = v

    # Distribute remaining broadcast extra_params to every step so that
    # each handler can pick up the fields it needs.
    if extra:
        for step_dict in step_dicts:
            step_dict["params"].update(extra)

    # Build engine Steps
    steps = [
        Step(
            number=sd["step"],
            action=sd["action"],
            params=sd["params"],
            description=sd["description"],
            is_destructive=sd["is_destructive"],
            for_each=sd.get("for_each"),
        )
        for sd in step_dicts
    ]

    wf_name = workflow_name or "dynamic_workflow"
    desc = description or f"Dynamic workflow: {' → '.join(action_list)}"

    plan = create_plan(workflow_name=wf_name, description=desc, steps=steps)

    has_destructive = any(s.is_destructive for s in steps)
    plan.status = PlanStatus.AWAITING_APPROVAL if has_destructive else PlanStatus.DRAFT

    session = get_session()
    session.plans[plan.plan_id] = plan

    preview = plan.to_preview()
    logger.info(f"Built dynamic plan {plan.plan_id} with {len(steps)} steps")

    if has_destructive:
        hint = (
            f"Plan has {len(steps)} steps "
            f"({len(preview['destructive_steps'])} destructive). "
            f"Requires approval. Call orchestrator_execute(plan_id='{plan.plan_id}') to run it."
        )
    else:
        hint = (
            f"Plan has {len(steps)} steps (no destructive actions). "
            f"Safe to execute. Call orchestrator_execute(plan_id='{plan.plan_id}') to run it."
        )

    return {
        "plan": preview,
        "wiring": step_dicts,
        "hint": hint,
    }


@mcp.tool()
async def orchestrator_execute(
    ctx: Context,
    plan_id: str,
    param_overrides: Optional[dict] = None,
) -> dict:
    """Execute an approved workflow plan server-side.

    Call this AFTER orchestrator_plan_for_goal returns a plan_id.
    The server runs every step internally against the Okta API — no
    round-trips back to the LLM.  Inter-step data flow (e.g. user ID
    from step 1 feeds into step 2) is resolved automatically via the
    knowledge graph's predicate wiring.

    Do NOT call this without a plan — call orchestrator_plan_for_goal first.

    Parameters:
        plan_id (str, required): The plan ID returned by orchestrator_plan_for_goal.
            Found in the response under plan → plan_id.
        param_overrides (dict, optional): A dict mapping step numbers (as strings)
            to dicts of parameter overrides. These are merged into the step's params
            before execution. Use this to supply data the planner cannot auto-wire,
            such as request_data, campaign_data, or filter expressions.
            Example: {"1": {"request_data": {"name": "Test", "type": "APP"}}}

    Returns:
        Dict with step-by-step execution results, context, and a summary.

    Example:
        # Step 1 — get a plan:
        result = orchestrator_plan_for_goal(
            goal_state="user.apps=AUDITED,user.group_memberships=REVOKED,user.sessions=REVOKED,user.status=DEACTIVATED",
            initial_state="user.identifier=PROVIDED",
            target_identifier="john@acme.com"
        )
        plan_id = result["plan"]["plan_id"]

        # Step 2 — execute it:
        orchestrator_execute(plan_id=plan_id)

        # With param overrides (e.g. for governance request creation):
        orchestrator_execute(
            plan_id=plan_id,
            param_overrides={"1": {"request_data": {"name": "Test Request"}}}
        )
    """
    logger.info(f"orchestrator_execute: plan_id='{plan_id}'")

    session = get_session()
    plan = session.plans.get(plan_id)

    if not plan:
        return {
            "error": f"Plan '{plan_id}' not found. Call orchestrator_plan_for_goal first to create a plan.",
            "active_plans": [
                {"plan_id": p.plan_id, "workflow": p.workflow_name, "status": p.status.value}
                for p in session.plans.values()
            ],
        }

    if plan.status not in (PlanStatus.DRAFT, PlanStatus.AWAITING_APPROVAL):
        return {
            "error": f"Plan '{plan_id}' is in state '{plan.status.value}' and cannot be executed.",
            "summary": plan.to_summary(),
        }

    # Apply param_overrides if provided
    if param_overrides:
        try:
            overrides = param_overrides
            for step in plan.steps:
                step_key = str(step.number)
                if step_key in overrides and isinstance(overrides[step_key], dict):
                    step.params.update(overrides[step_key])
                    logger.info(f"Plan {plan_id}: Applied param overrides to step {step.number}: {list(overrides[step_key].keys())}")
        except (ValueError, TypeError) as exc:
            return {"error": f"Invalid param_overrides: {exc}"}

    manager = ctx.request_context.lifespan_context.okta_auth_manager

    try:
        plan = await execute_plan(plan, manager)
    except Exception as exc:
        logger.error(f"Plan execution failed: {exc}")
        return {"error": f"Plan execution failed: {exc}"}

    summary = plan.to_summary()
    context = _build_execution_context(plan)
    logger.info(f"Plan {plan_id} completed: {plan.status.value}")

    return {
        "summary": summary,
        "context": context,
        "hint": (
            f"Workflow '{plan.workflow_name}' {plan.status.value}. "
            f"Call orchestrator_context() for full session state."
        ),
    }


@mcp.tool()
async def orchestrator_context(ctx: Context) -> dict:
    """Get the current orchestrator session state and graph stats.

    Use this to:
    - Check what has already been done in this session.
    - Retrieve results from previously executed plans.
    - See which plans are still pending execution.
    - Answer follow-up questions without calling the Okta API again.

    No parameters — returns everything about the current session.

    Returns:
        Dict with session data, active plans, and graph capabilities.
    """
    logger.info("orchestrator_context invoked")

    session = get_session()
    kg = get_knowledge_graph()

    active_plans = [
        {"plan_id": p.plan_id, "workflow": p.workflow_name, "status": p.status.value}
        for p in session.plans.values()
        if p.status in (PlanStatus.DRAFT, PlanStatus.AWAITING_APPROVAL)
    ]

    return {
        "session": session.to_dict(),
        "active_plans": active_plans,
        "graph_stats": kg.get_stats(),
        "hint": (
            "To start a new workflow, call orchestrator_plan_for_goal() with a "
            "goal_state and target_identifier. "
            "To run a pending plan, call orchestrator_execute(plan_id='...')."
        ),
    }


@mcp.tool()
async def orchestrator_plan_for_goal(
    ctx: Context,
    goal_state: Optional[str] = None,
    initial_state: Optional[str] = None,
    target_identifier: Optional[str] = None,
    extra_params: Optional[str] = None,
) -> dict:
    """Plan an Okta workflow using the CSP constraint solver.

    PRIMARY ENTRY POINT for multi-step Okta ops. Builds a plan only —
    call orchestrator_execute(plan_id=...) to run it. The solver works
    backward from your goal, finding the minimal action sequence automatically.

    PARAMETERS
      goal_state:        "entity.property=VALUE,..." — desired end-state predicates
      initial_state:     what is already known/provided (often auto-inferred)
      target_identifier: primary entity email/ID/name (feeds the first step)
      extra_params:      "key=value,..." broadcast to all steps

    PREDICATES — USER
      user.identifier=PROVIDED | user.profile_data=PROVIDED
      user.id=KNOWN | user.profile=KNOWN|UPDATED | user.schema=KNOWN
      user.status=KNOWN|CREATED|ACTIVE|SUSPENDED|DEACTIVATED|DELETED|PROVISIONED|UNLOCKED
      user.list=KNOWN | user.apps=AUDITED | user.groups=ENUMERATED
      user.group_membership=GRANTED | user.group_memberships=REVOKED | user.sessions=REVOKED
      user.password=EXPIRED|CHANGED|RESET | user.temp_password=KNOWN | user.reset_url=KNOWN
      user.recovery_question=CHANGED | user.password_reset=INITIATED
      user.factors=ENUMERATED|RESET | user.blocks=ENUMERATED | user.clients=ENUMERATED
      user.devices=ENUMERATED | user.grants=ENUMERATED|REVOKED
      user.refresh_tokens=ENUMERATED|REVOKED | user.risk_level=KNOWN|UPDATED
      user.classification=KNOWN|UPDATED | user.linked_objects=ENUMERATED
      user.authenticator_enrollments=ENUMERATED
      factor.id=KNOWN|DELETED | factor.status=KNOWN
      user_grant.id=KNOWN|REVOKED | user_type.list=KNOWN | user_type.id=KNOWN|DELETED

    PREDICATES — GROUP
      group.identifier=PROVIDED | group.profile_data=PROVIDED
      group.id=KNOWN | group.profile=KNOWN|UPDATED
      group.status=CREATED|DELETED | group.list=KNOWN
      group.users=ENUMERATED | group.apps=ENUMERATED
      group.owners=ENUMERATED | group.owner=ASSIGNED|REMOVED
      group_rule.list=KNOWN | group_rule.id=KNOWN|DELETED
      group_rule.status=KNOWN|ACTIVE|INACTIVE | group_rule.profile=UPDATED

    PREDICATES — APP
      application.identifier=PROVIDED | application.id=KNOWN
      application.profile=KNOWN|UPDATED
      application.status=CREATED|ACTIVE|DEACTIVATED|DELETED | application.list=KNOWN

    PREDICATES — POLICY
      policy.identifier=PROVIDED | policy.id=KNOWN | policy.profile=KNOWN|UPDATED
      policy.status=CREATED|ACTIVE|DEACTIVATED|DELETED | policy.list=KNOWN
      policy.rules=ENUMERATED | policy.simulation_result=KNOWN | policy.apps=ENUMERATED
      policy.cloned_id=KNOWN | policy.resource_mappings=ENUMERATED | policy.resource_mapping=CREATED
      policy_rule.id=KNOWN|DELETED | policy_rule.profile=KNOWN|UPDATED
      policy_rule.status=CREATED|ACTIVE|DEACTIVATED|DELETED

    PREDICATES — BRAND / THEME
      brand.identifier=PROVIDED | brand.id=KNOWN | brand.profile=KNOWN|UPDATED
      brand.status=CREATED|DELETED | brand.list=KNOWN | brand.domains=ENUMERATED
      theme.id=KNOWN | theme.profile=KNOWN|UPDATED | theme.list=KNOWN
      theme.logo=UPLOADED|DELETED | theme.favicon=UPLOADED|DELETED | theme.background=UPLOADED

    PREDICATES — CUSTOM DOMAIN / EMAIL DOMAIN
      custom_domain.data=PROVIDED | custom_domain.certificate_data=PROVIDED
      custom_domain.id=KNOWN | custom_domain.profile=KNOWN|UPDATED
      custom_domain.status=CREATED|VERIFIED|DELETED | custom_domain.list=KNOWN
      custom_domain.certificate=CONFIGURED
      email_domain.data=PROVIDED | email_domain.id=KNOWN | email_domain.profile=KNOWN|UPDATED
      email_domain.status=CREATED|VERIFIED|DELETED | email_domain.list=KNOWN

    PREDICATES — CUSTOM PAGE
      custom_page.sign_in_page=KNOWN|UPDATED|DELETED | custom_page.sign_in_page_default=KNOWN
      custom_page.sign_in_page_preview=KNOWN|UPDATED|DELETED | custom_page.sign_in_page_resources=KNOWN
      custom_page.error_page=KNOWN|UPDATED|DELETED | custom_page.error_page_default=KNOWN
      custom_page.error_page_preview=KNOWN|UPDATED|DELETED | custom_page.error_page_resources=KNOWN
      custom_page.sign_out_settings=KNOWN|UPDATED | custom_page.widget_versions=KNOWN

    PREDICATES — EMAIL TEMPLATE
      email_template.id=KNOWN | email_template.profile=KNOWN | email_template.list=KNOWN
      email_template.settings=KNOWN|UPDATED | email_template.default_content=KNOWN
      email_template.default_content_preview=KNOWN | email_template.customization_id=KNOWN
      email_template.customization=CREATED|DELETED | email_template.customization_profile=KNOWN|UPDATED
      email_template.customization_preview=KNOWN | email_template.customizations=ENUMERATED|DELETED
      email_template.test_email=SENT

    PREDICATES — DEVICE
      device.list=KNOWN | device.id=KNOWN|DELETED
      device.status=KNOWN|ACTIVE|DEACTIVATED|SUSPENDED | device.users=ENUMERATED
      device_integration.list=KNOWN | device_integration.id=KNOWN
      device_integration.status=ACTIVE|DEACTIVATED
      device_posture_check.list=KNOWN | device_posture_check.id=KNOWN|DELETED
      device_posture_check.profile=UPDATED
      device_assurance.data=PROVIDED | device_assurance.id=KNOWN
      device_assurance.profile=KNOWN|UPDATED
      device_assurance.status=CREATED|DELETED | device_assurance.list=KNOWN

    PREDICATES — LOG STREAM / PROFILE MAPPING / LOGS
      log_stream.list=KNOWN | log_stream.id=KNOWN|DELETED
      log_stream.status=KNOWN|ACTIVE|DEACTIVATED | log_stream.profile=UPDATED
      profile_mapping.list=KNOWN | profile_mapping.id=KNOWN | profile_mapping.profile=UPDATED
      log.events=RETRIEVED

    PREDICATES — GOVERNANCE
      gov_request_condition.list=KNOWN | gov_request_condition.id=KNOWN|DELETED
      gov_request_condition.status=ACTIVE|INACTIVE
      gov_request.list=KNOWN | gov_request.id=KNOWN | gov_request.details=KNOWN
      gov_request.my_request_id=KNOWN
      gov_catalog.entries=KNOWN | gov_catalog.entry_id=KNOWN
      gov_catalog.user_entries=KNOWN | gov_catalog.my_entries=KNOWN | gov_catalog.my_entry_id=KNOWN
      gov_campaign.list=KNOWN | gov_campaign.id=KNOWN|DELETED
      gov_campaign.status=KNOWN|LAUNCHED|ENDED
      gov_review.list=KNOWN | gov_review.id=KNOWN | gov_review.reassignment=DONE
      gov_entitlement.list=KNOWN | gov_entitlement.id=KNOWN|DELETED | gov_entitlement.values=ENUMERATED
      gov_entitlement_bundle.list=KNOWN | gov_entitlement_bundle.id=KNOWN|DELETED
      gov_collection.list=KNOWN | gov_collection.id=KNOWN|DELETED
      gov_collection.resources=ENUMERATED | gov_collection.assignments=ENUMERATED
      gov_grant.list=KNOWN | gov_grant.id=KNOWN
      gov_principal_entitlement.list=KNOWN | gov_principal_entitlement.history=KNOWN
      gov_principal_entitlement.access=REVOKED
      gov_label.list=KNOWN | gov_label.id=KNOWN|DELETED | gov_label.resources=KNOWN
      gov_resource_owner.list=KNOWN | gov_resource_owner.unowned=KNOWN
      gov_delegate.list=KNOWN | gov_delegate.my_eligible=KNOWN
      gov_settings.my_settings=KNOWN|UPDATED

    FILTER / SEARCH / Q
      filter: Okta Expression Language — '<field> eq "<value>"' joined with ' and '
        Users:  status eq "ACTIVE|SUSPENDED|DEPROVISIONED", memberOf.id eq "00g..."
        Groups: type eq "OKTA_GROUP|APP_GROUP|BUILT_IN"
        Logs:   actor.id eq "...", target.id eq "...", eventType eq "..."
        Apps:   status eq "ACTIVE|INACTIVE"
      search: SCIM — 'profile.<attr> eq|sw|co "<value>"' or 'status eq "ACTIVE"'
              (list_users and list_groups only)
      q:      prefix match on name/email (plain string)
      Policies require: type=OKTA_SIGN_ON|PASSWORD|MFA_ENROLL|ACCESS_POLICY|PROFILE_ENROLLMENT|IDP_DISCOVERY
      Auto-wired: get_user→get_logs (actor.id), get_group→get_logs (target.id),
                  get_group→list_users (memberOf.id)

    EXTRA PARAMS KEYS
      filter, search, q, since, until, type, status, name, description,
      send_email, expand, limit
      Action-targeted:    "@action_name:key=value" — injects param into one step only
      Profile auto-bundle: name/description/firstName/lastName/email/login/
        mobilePhone/secondEmail/displayName/nickName/title/department/organization/userType
        → auto-bundled into profile{} when first step needs it
      Commas are delimiters — values cannot contain commas

    WARNINGS
      • No "context" param — secondary entity IDs go in extra_params
      • get_group requires group_id (00g...) not name — use list_groups with q= to find by name
      • Primary entity → target_identifier | Secondary entity → extra_params

    """
    if not goal_state:
        return {
            "error": "goal_state is required. Provide comma-separated predicates like 'user.status=DEACTIVATED,user.sessions=REVOKED'.",
            "hint": "Use orchestrator_context() to inspect the knowledge graph for available predicates.",
        }

    # Parse initial_state if provided
    init_state: dict[str, str] | None = None
    if initial_state:
        init_state = {}
        for pair in initial_state.split(","):
            pair = pair.strip()
            if "=" in pair:
                k, v = pair.split("=", 1)
                init_state[k.strip()] = v.strip()

    logger.info(f"orchestrator_plan_for_goal: "
                f"goal_state='{goal_state}', target='{target_identifier}'")

    kg = get_knowledge_graph()

    # Parse goal_state
    parsed_goal: dict[str, str] = {}
    for pair in (goal_state or "").split(","):
        pair = pair.strip()
        if "=" in pair:
            k, v = pair.split("=", 1)
            parsed_goal[k.strip()] = v.strip()
    if not parsed_goal:
        return {"error": "Invalid goal_state format. Use 'key=value,key=value'."}
    result = plan_for_state(parsed_goal, initial_state=init_state, kg=kg)

    if not result.success:
        return {
            "success": False,
            "error": result.error,
            "goal": "ad_hoc",
            "hint": "The planner could not find a valid action sequence for this goal.",
        }

    response: dict = {
        "success": True,
        "solver_result": result.to_dict(),
    }

    # ── Build an executable plan ──
    if result.actions:
        wf_name = "csp_workflow"
        desc = f"CSP-planned workflow: {' → '.join(result.actions)}"

        # Reuse the existing build_plan logic
        try:
            step_dicts = kg.build_execution_chain(result.actions)
        except ValueError as exc:
            response["build_error"] = str(exc)
            return response

        # Parse extra_params with optional action-targeting.
        # Syntax:  key=value               → broadcast to all steps
        #          @action_name:key=value   → only inject into that action's step
        extra: dict = {}
        targeted_params: dict[str, dict[str, str]] = {}  # action → {key: value}
        if extra_params:
            for pair in extra_params.split(","):
                if "=" in pair:
                    k, v = pair.split("=", 1)
                    k = k.strip()
                    v = v.strip()
                    if k.startswith("@") and ":" in k:
                        action_target, real_key = k[1:].split(":", 1)
                        targeted_params.setdefault(
                            action_target.strip(), {}
                        )[real_key.strip()] = v
                    else:
                        extra[k] = v

        # Inject target identifier into the first step's required params
        # (only when the first step actually needs input and a target was given)
        first_node = kg.get_node(result.actions[0])
        # Profile fields that should be bundled into a dict, not set as scalars
        _PROFILE_FIELDS = {
            "firstName", "lastName", "email", "login", "mobilePhone",
            "secondEmail", "displayName", "nickName", "title",
            "department", "organization", "userType",
            "name", "description",
        }
        if first_node and target_identifier:
            if first_node.required_params:
                for param in first_node.required_params:
                    if param == "profile" and extra.keys() & _PROFILE_FIELDS:
                        # Build a profile dict from extra_params profile fields
                        profile_dict = {k: extra.pop(k) for k in list(extra) if k in _PROFILE_FIELDS}
                        step_dicts[0]["params"]["profile"] = profile_dict
                    else:
                        step_dicts[0]["params"][param] = target_identifier
            else:
                # P1 fix: first step has no required params — inject
                # target_identifier into the first identifier-like optional param.
                for param in (first_node.optional_params or []):
                    if param.endswith("_id") or param == "name":
                        step_dicts[0]["params"][param] = target_identifier
                        break
            if init_state:
                for param in (first_node.optional_params or []):
                    if param in init_state:
                        step_dicts[0]["params"][param] = init_state[param]
        elif first_node and not target_identifier:
            # No target_identifier — still build profile dict from extra_params
            # if the first step requires a 'profile' param (e.g. create_group).
            if first_node.required_params:
                for param in first_node.required_params:
                    if param == "profile" and extra.keys() & _PROFILE_FIELDS:
                        profile_dict = {k: extra.pop(k) for k in list(extra) if k in _PROFILE_FIELDS}
                        step_dicts[0]["params"]["profile"] = profile_dict

        # P3 fix: inject target_identifier into secondary entity-resolution
        # steps whose required params are not auto-wired from upstream.
        # Only when the step has an identifier precondition and a single
        # unresolved required param.
        if target_identifier and len(result.actions) > 1:
            for idx, action_name in enumerate(result.actions[1:], start=1):
                node = kg.get_node(action_name)
                if not node:
                    continue
                # Only entity-resolution steps (precondition = *.identifier=PROVIDED)
                has_id_precondition = any(
                    k.endswith(".identifier") and v == "PROVIDED"
                    for k, v in node.preconditions.items()
                )
                if not has_id_precondition:
                    continue
                # Collect required params not already wired by build_execution_chain
                unresolved = [
                    p for p in node.required_params
                    if p not in step_dicts[idx]["params"]
                ]
                # Also check identifier-like optional params if no required params
                if not node.required_params:
                    unresolved = [
                        p for p in (node.optional_params or [])
                        if (p.endswith("_id") or p == "name")
                        and p not in step_dicts[idx]["params"]
                    ]
                # Only inject when targeted params or extra provide the identifier;
                # never blindly duplicate target_identifier into secondary steps
                # (that would give the wrong entity). Instead, check targeted_params
                # and extra for matching param names.
                for p in unresolved:
                    if action_name in targeted_params and p in targeted_params[action_name]:
                        step_dicts[idx]["params"][p] = targeted_params[action_name].pop(p)
                    elif p in extra:
                        step_dicts[idx]["params"][p] = extra[p]

        # P2 fix: apply action-targeted params to their specific steps.
        if targeted_params:
            for step_dict in step_dicts:
                action_name = step_dict["action"]
                if action_name in targeted_params:
                    for k, v in targeted_params[action_name].items():
                        step_dict["params"][k] = v

        # Distribute remaining broadcast extra_params to every step so each
        # handler can pick up the fields it needs (e.g. name= for get_group).
        # Handlers simply ignore params they don't use.
        if extra:
            for step_dict in step_dicts:
                for k, v in extra.items():
                    if k not in step_dict["params"]:
                        step_dict["params"][k] = v

        steps = [
            Step(
                number=sd["step"],
                action=sd["action"],
                params=sd["params"],
                description=sd["description"],
                is_destructive=sd["is_destructive"],
                for_each=sd.get("for_each"),
            )
            for sd in step_dicts
        ]

        plan = create_plan(workflow_name=wf_name, description=desc, steps=steps)
        has_destructive = any(s.is_destructive for s in steps)
        plan.status = PlanStatus.AWAITING_APPROVAL if has_destructive else PlanStatus.DRAFT

        session = get_session()
        session.plans[plan.plan_id] = plan

        response["plan"] = plan.to_preview()
        response["wiring"] = step_dicts
        response["hint"] = (
            f"CSP solver found {len(result.actions)}-step plan. "
            f"Call orchestrator_execute(plan_id='{plan.plan_id}') to run it."
        )

    return response


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_execution_context(plan: Plan) -> dict:
    """Extract key information from plan results into a readable context."""
    context: dict = {
        "workflow": plan.workflow_name,
        "status": plan.status.value,
        "actions_taken": [],
    }

    for step in plan.steps:
        result_data = plan.results.get(step.number)
        if result_data is None:
            continue

        serialised = _serialise(result_data)

        if step.action == "get_user" and isinstance(serialised, dict):
            profile = serialised.get("profile", {})
            context["user"] = {
                "id": serialised.get("id"),
                "login": profile.get("login"),
                "email": profile.get("email"),
                "name": f"{profile.get('firstName', '')} {profile.get('lastName', '')}".strip(),
                "status": serialised.get("status"),
            }
            context["actions_taken"].append(
                f"Found user: {profile.get('email', serialised.get('id'))}"
            )

        elif step.action == "list_user_groups" and isinstance(serialised, list):
            group_names = []
            for g in serialised:
                gs = _serialise(g) if not isinstance(g, dict) else g
                if isinstance(gs, dict) and "profile" in gs:
                    group_names.append(gs["profile"].get("name", gs.get("id", "?")))
            context["groups_found"] = group_names
            context["actions_taken"].append(f"Found {len(group_names)} group memberships")

        elif step.action == "remove_user_from_group" and isinstance(serialised, list):
            context["groups_removed"] = len(serialised)
            context["actions_taken"].append(f"Removed from {len(serialised)} groups")

        elif step.action == "list_user_app_assignments" and isinstance(serialised, list):
            app_labels = []
            for a in serialised:
                a_s = _serialise(a) if not isinstance(a, dict) else a
                if isinstance(a_s, dict):
                    app_labels.append(a_s.get("label", a_s.get("appName", "?")))
            context["app_assignments"] = app_labels
            context["actions_taken"].append(f"Found {len(app_labels)} app assignments")

        elif step.action == "deactivate_user":
            context["actions_taken"].append("User account deactivated")

        elif step.action == "suspend_user":
            context["actions_taken"].append("User account suspended")

        elif step.action == "activate_user":
            context["actions_taken"].append("User account activated")

        elif step.action == "clear_user_sessions":
            context["actions_taken"].append("All sessions revoked")

        elif step.action == "add_user_to_group":
            context["actions_taken"].append("User added to target group")

        elif step.action == "get_group" and isinstance(serialised, dict):
            profile = serialised.get("profile", {})
            context["target_group"] = {
                "id": serialised.get("id"),
                "name": profile.get("name"),
            }
            context["actions_taken"].append(f"Found group: {profile.get('name')}")

    return context
